### ISSUE TITLE
Readme?

### ISSUE THREAD

**Issue by phseiff** [LociStar/ChessEngineCPP#1]
It would be quite fortunate if you added a REAMDe-file to your repository as well as (possibly) a license. If you don't want to license your code, you might want to add a LICENSE-file nonetheless, stating that no open-source-licensing is intended, to ensure you don't get constant questions about this the issues.

**Comment by LociStar** [comment]
readme-file added  - 4ef388098632e7cb26f801db24e02d03a860c240

Licence added - #2 


I am closing this issue.
